/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ans_PC
 */
public class Login_page extends javax.swing.JFrame {

    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents();
        // center the form
        this.setLocationRelativeTo(null);
        // Border for the title
        Border jlabel_title_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        title_label.setBorder(jlabel_title_border);
        
        //create a border for the create account jlabel
        
         Border jlabel_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_Create_Account.setBorder(jlabel_create_account_border);
        
        Border jlabel_admin_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);

        Admin_Login.setBorder(jlabel_admin_border);
        
        // Border for the minimize and close buttons
        panel_min.setBorder(jlabel_title_border);
        panel_close.setBorder(jlabel_title_border);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username_jfield = new javax.swing.JTextField();
        password_jfield = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        jLabel_Create_Account = new javax.swing.JLabel();
        Admin_Login = new javax.swing.JLabel();
        panel_min = new javax.swing.JLabel();
        panel_close = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        username_jfield.setForeground(new java.awt.Color(153, 153, 153));
        username_jfield.setText("username");
        username_jfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_jfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_jfieldFocusLost(evt);
            }
        });

        password_jfield.setForeground(new java.awt.Color(153, 153, 153));
        password_jfield.setText("password");
        password_jfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_jfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_jfieldFocusLost(evt);
            }
        });
        password_jfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_jfieldActionPerformed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(51, 255, 51));
        login_button.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_buttonMouseExited(evt);
            }
        });
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        jLabel_Create_Account.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Create_Account.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Create_Account.setText("You don't have an Account? Create One!");
        jLabel_Create_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Create_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseExited(evt);
            }
        });

        Admin_Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Admin_Login.setForeground(new java.awt.Color(255, 51, 51));
        Admin_Login.setText("Are you an Admin? Login Now!");
        Admin_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Admin_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admin_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admin_LoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_jfield)
                    .addComponent(password_jfield, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Create_Account)
                    .addComponent(Admin_Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(username_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(password_jfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addComponent(jLabel_Create_Account)))
                .addGap(38, 38, 38)
                .addComponent(Admin_Login)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panel_min.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        panel_min.setText("-");
        panel_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_minMouseExited(evt);
            }
        });

        panel_close.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        panel_close.setText("X");
        panel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_closeMouseExited(evt);
            }
        });

        title_label.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        title_label.setText("Welcome back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_label)
                .addGap(204, 204, 204)
                .addComponent(panel_min, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(panel_min)
                        .addComponent(panel_close))
                    .addComponent(title_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_minMouseEntered
        // TODO add your handling code here:
        Border jlabel_min = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        panel_min.setBorder(jlabel_min);
        panel_min.setForeground(Color.white);
    }//GEN-LAST:event_panel_minMouseEntered

    private void panel_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_minMouseExited
        // TODO add your handling code here:
        Border jlabel_min = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        panel_min.setBorder(jlabel_min);
        panel_min.setForeground(Color.black);
    }//GEN-LAST:event_panel_minMouseExited

    private void panel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_closeMouseEntered
        // TODO add your handling code here:
        Border jlabel_close = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        panel_close.setBorder(jlabel_close);
        panel_close.setForeground(Color.white);
    }//GEN-LAST:event_panel_closeMouseEntered

    private void panel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_closeMouseExited
        // TODO add your handling code here:
        Border jlabel_close = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        panel_close.setBorder(jlabel_close);
        panel_close.setForeground(Color.black);
    }//GEN-LAST:event_panel_closeMouseExited

    private void password_jfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_jfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_jfieldActionPerformed

    private void username_jfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_jfieldFocusGained
        // TODO add your handling code here:
        if(username_jfield.getText().trim().toLowerCase().equals("username"))
        {
            username_jfield.setText("");
            username_jfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_username_jfieldFocusGained

    private void username_jfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_jfieldFocusLost
        // TODO add your handling code here:
        if(username_jfield.getText().trim().toLowerCase().equals("username") || 
           username_jfield.getText().trim().equals(""))
        {
            username_jfield.setText("username");
            username_jfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_username_jfieldFocusLost

    private void password_jfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_jfieldFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(password_jfield.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            password_jfield.setText("");
            password_jfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_password_jfieldFocusGained

    private void password_jfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_jfieldFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(password_jfield.getPassword());
        if(pass.trim().toLowerCase().equals("username") || 
           pass.trim().equals(""))
        {
            password_jfield.setText("password");
            password_jfield.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_password_jfieldFocusLost

    private void login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseEntered
        // TODO add your handling code here:
        login_button.setBackground(new Color(0,151,0));
    }//GEN-LAST:event_login_buttonMouseEntered

    private void login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseExited
        // TODO add your handling code here:
        login_button.setBackground(new Color(51,255,51));
    }//GEN-LAST:event_login_buttonMouseExited

    private void panel_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_panel_minMouseClicked

    private void panel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_panel_closeMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        
        String username = username_jfield.getText();
        String password = String.valueOf(password_jfield.getPassword());
        
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                // show a new form
                Menu form = new Menu();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
            }else{
             // error message  
             JOptionPane.showMessageDialog(null, "invalid username/password", "Login error", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void jLabel_Create_AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseEntered
       
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        jLabel_Create_Account.setBorder(label_border);
    }//GEN-LAST:event_jLabel_Create_AccountMouseEntered

    private void jLabel_Create_AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseExited
       
        Border jlabel_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        jLabel_Create_Account.setBorder(jlabel_create_account_border);
        
    }//GEN-LAST:event_jLabel_Create_AccountMouseExited

    private void jLabel_Create_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseClicked
        
        Register_form rf = new Register_form();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_Create_AccountMouseClicked

    private void Admin_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LoginMouseClicked
              
        Admin_Login ad = new Admin_Login();
        ad.setVisible(true);
        ad.pack();
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        
    }//GEN-LAST:event_Admin_LoginMouseClicked

    private void Admin_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LoginMouseEntered
       
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0,Color.red);
        Admin_Login.setBorder(label_border);

        
    }//GEN-LAST:event_Admin_LoginMouseEntered

    private void Admin_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LoginMouseExited
               
        Border jlabel_create_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        Admin_Login.setBorder(jlabel_create_account_border);


    }//GEN-LAST:event_Admin_LoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Create_Account;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel panel_close;
    private javax.swing.JLabel panel_min;
    private javax.swing.JPasswordField password_jfield;
    private javax.swing.JLabel title_label;
    private javax.swing.JTextField username_jfield;
    // End of variables declaration//GEN-END:variables
}
