/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author sirag
 */
public class Rent_Vehicle extends javax.swing.JFrame {
String v_type;
    /**
     * Creates new form Rent_Vehicle
     */
    public Rent_Vehicle() {
        initComponents();
         //jTextField_id1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_Luxury = new javax.swing.JRadioButton();
        jDateChooser_In = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser_Out = new com.toedter.calendar.JDateChooser();
        jRadioButton_Standard = new javax.swing.JRadioButton();
        jTextField_lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_persons = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField_fname = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton_Car = new javax.swing.JRadioButton();
        jDateChooser_Start = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser_Return = new com.toedter.calendar.JDateChooser();
        jRadioButton_MotorCycle = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField_license = new javax.swing.JTextField();
        jTextField_id1 = new javax.swing.JTextField();
        jRadioButton_Van = new javax.swing.JRadioButton();
        jRadioButton_ATV = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Cost = new javax.swing.JButton();
        jButton_Rent = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Your Reservation id is: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Check In:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Check Out:");

        jRadioButton_Luxury.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Luxury.setText("Luxury Room");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Type of Room:");

        jRadioButton_Standard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Standard.setText("Standard Room");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("First Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("No.Of Persons:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Last Name:");

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RENT A VEHICLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Enter your Reservation ID:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Start Date:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Return Date:");

        buttonGroup1.add(jRadioButton_Car);
        jRadioButton_Car.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Car.setText("Car");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Type of Vehicle:");

        buttonGroup1.add(jRadioButton_MotorCycle);
        jRadioButton_MotorCycle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_MotorCycle.setText("MotorCycle");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Driver License ID:");

        jTextField_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_id1ActionPerformed(evt);
            }
        });
        jTextField_id1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_id1KeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Van);
        jRadioButton_Van.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_Van.setText("Van");
        jRadioButton_Van.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_VanActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_ATV);
        jRadioButton_ATV.setText("ATV");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Rent a Vehicle and Save Time and Money with our unique Discounts !! ");

        jButton_Cancel.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Cost.setBackground(new java.awt.Color(255, 255, 153));
        jButton_Cost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Cost.setText("Calculate Cost");
        jButton_Cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CostActionPerformed(evt);
            }
        });

        jButton_Rent.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Rent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Rent.setText("Rent");
        jButton_Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton_MotorCycle)
                        .addGap(55, 55, 55)
                        .addComponent(jRadioButton_Car)
                        .addGap(58, 58, 58)
                        .addComponent(jRadioButton_Van)
                        .addGap(56, 56, 56)
                        .addComponent(jRadioButton_ATV))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_license, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_Start, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_Return, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jButton_Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField_license, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jDateChooser_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel14)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15))
                    .addComponent(jDateChooser_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton_MotorCycle)
                    .addComponent(jRadioButton_Car)
                    .addComponent(jRadioButton_Van)
                    .addComponent(jRadioButton_ATV))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_id1ActionPerformed

    private void jRadioButton_VanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_VanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_VanActionPerformed

    private void jButton_CostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CostActionPerformed
     if(verifyFields()){
        if(checkCode(jTextField_id1.getText()))
     {
         
        double res_cost = calculate_reservation_cost();
        double veh_cost = calculate_vehicle_cost();
        double total = res_cost + veh_cost ;
        double disc_total = total -( total *0.2 );
        JOptionPane.showMessageDialog(null, "Reservation Cost is :" + res_cost +"\n Vehicle Cost is :" + veh_cost + "\n Total Cost is :" + total + "\n Total Cost after 20% Discount is : " +  disc_total );
     }
     }
    }//GEN-LAST:event_jButton_CostActionPerformed

    private void jTextField_id1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_id1KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();

        }
        
    }//GEN-LAST:event_jTextField_id1KeyTyped

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
       
        Payment pk = new Payment();
        pk.setVisible(true);
        pk.pack();
        pk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RentActionPerformed
        
         if(verifyFields())
         {  
                
            int opt = JOptionPane.showConfirmDialog(null, "Your Reservation will be made and you will be directed to the payment page ", "Confirmation", JOptionPane.YES_NO_OPTION);
            if(opt==0)
            {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        
         String lic_id = jTextField_license.getText();
         String start_date = (df.format(jDateChooser_Start.getDate()));
         String return_date = (df.format(jDateChooser_Return.getDate()));
         String res_id = jTextField_id1.getText(); 
       
         
             PreparedStatement ps ;
                 ResultSet rs; 
                 String registerUserQuery = "INSERT INTO `vehicle_reservation`(`License_id`, `Start_date`, `Return_Date`, `Veh_type`, `Res_id`) VALUES (?,?,?,?,?)";
                 
                 try {
                     
                     ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                     
                     ps.setString(1, lic_id);
                     ps.setString(2, start_date);
                     ps.setString(3, return_date);
                     
                     if(jRadioButton_MotorCycle.isSelected()){
                         v_type = "MotorCycle";
                     }
                     if(jRadioButton_Car.isSelected()){
                         v_type = "Car";
                     }
                     if(jRadioButton_Van.isSelected()){
                         v_type = "Van";
                     }
                     if(jRadioButton_ATV.isSelected()){
                         v_type = "ATV";
                     }
                     ps.setString(4,v_type);
                     ps.setString(5, res_id);
                                                              
                     if(ps.executeUpdate() != 0)
                     {
                         try{
                         String myDriver = "com.mysql.cj.jdbc.Driver";
                         String myUrl = "jdbc:mysql://localhost/hotel_system";
                         Class.forName(myDriver);
                         Connection con = DriverManager.getConnection(myUrl, "root", "");
                         
                         String query = "select Veh_id from vehicle_reservation ORDER BY (Veh_id) DESC LIMIT 1";
                           try (Statement stmt = con.createStatement()) {
                            ResultSet rt = stmt.executeQuery(query);
                        while (rt.next()) {
                        String id = rt.getString("Veh_id");
                        
                         JOptionPane.showMessageDialog(null, "Your Vehicle Reservation has been made and your Reservation Code is " + id );
                         
                         String msg = jTextField_id1.getText();
                         
                         new Payment(msg).setVisible(true);
                         this.dispose();
                         //Payment pk = new Payment();
                         //pk.setVisible(true);
                         //pk.pack();
                         //pk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                         //this.dispose();
                            }
                            }catch (Exception e)
                            {
                             System.err.println("Got an exception! ");
                                System.err.println(e.getMessage());
                            }
                       }catch (Exception e)
                            {
                             System.err.println("Got an exception! ");
                                System.err.println(e.getMessage());
                            }}
                     else{
                         JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                     }
                         
                         
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
                 }
   
             
         }
        

    }                                        

            
        
    }//GEN-LAST:event_jButton_RentActionPerformed

   
    public double calculate_reservation_cost()
    {   
        double res_cost = 0;
        double Standard_cost = 40;
        double Luxury_cost = 70;
        
        String id = jTextField_id1.getText();
        String fname,lname,email,checkin,checkout,persons,type;
         try{
            String myDriver = "com.mysql.cj.jdbc.Driver";
            String myUrl = "jdbc:mysql://localhost/hotel_system";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
                         
            PreparedStatement ps ;
            String query = "SELECT * FROM reservations WHERE id =?  ";
            ps = My_CNX.getConnection().prepareStatement(query);
            //PreparedStatement myStmt = conn.PreparedStatement("SELECT * FROM reservations WHERE id =? ");
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
              
              fname =  rs.getString("first_name");
              lname= rs.getString("last_name");
              email =  rs.getString("email");
              checkin = rs.getString("check_in");
              checkout =  rs.getString("check_out");
              persons = rs.getString("Persons");
              type = rs.getString("Room_Type");
                              
             int diff = dateDiffernce(checkin,checkout);
             //JOptionPane.showMessageDialog(null, "Days differnce" + diff );
             
             if(type.equals("Standard"))
             {
                 res_cost = diff * Standard_cost;                 
             }
             else if (type.equals("Luxury"))
             {
                 res_cost = diff *Luxury_cost;
             }
            }
        
            
        }
        
        catch (Exception e)
            {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
            }
        
            return res_cost;
    }
    
    public int dateDiffernce(String date1 ,String date2) { 
        int i = 0;
    try{
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date firstdate = df.parse(date1);
        Date seconddate = df.parse(date2);  
        
        long diffInMillies = Math.abs(firstdate.getTime() - seconddate.getTime());
        
        //To diff exei thn diafora twn hmerwn
        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS); 
         i = (int) diff;

    }
     catch(Exception e){
            e.printStackTrace();
        }
    return i;
    }
    
    
    public double calculate_vehicle_cost()
    {
        double motor_cost = 25 ;
        double car_cost = 45 ;
        double ATV_cost = 35 ;
        double van_cost = 60;
        
        double vehicle_cost = 0;
        
        try{
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date firstdate = jDateChooser_Start.getDate();
        Date seconddate = jDateChooser_Return.getDate();  
        
        long diffInMillies = Math.abs(seconddate.getTime() - firstdate.getTime());
        
        //To diff exei thn diafora twn hmerwn
        long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS); 
                
        if(jRadioButton_MotorCycle.isSelected())
        {
            vehicle_cost = diff * motor_cost; 
        }
        
        if(jRadioButton_Car.isSelected())
        {
            vehicle_cost = diff * car_cost; 
        }
        
        if(jRadioButton_Van.isSelected())
        {
            vehicle_cost = diff * van_cost; 
        }
        
        if(jRadioButton_ATV.isSelected())
        {
            vehicle_cost = diff * ATV_cost; 
        }
        
        } catch(Exception e){
            e.printStackTrace();
        }
    
        return vehicle_cost;
    }
    
    
     public boolean verifyFields()
    {
        
         DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
         String id = jTextField_id1.getText();
         String license = jTextField_license.getText();
         
        // String start_date = (df.format(jDateChooser_Start.getDate()));
         //String return_date = (df.format(jDateChooser_Return.getDate()));
         
         Date start_date,return_date;
         start_date = jDateChooser_Start.getDate();
         return_date = jDateChooser_Return.getDate();

        //check empty fields
        if(id.trim().equals("") || license.trim().equals("") || (start_date == null) || (return_date == null) || (!(jRadioButton_MotorCycle.isSelected()) && !(jRadioButton_Car.isSelected()) && !(jRadioButton_Van.isSelected()) && !(jRadioButton_ATV.isSelected()) ))
            
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        else {
            
            return true;
        }
    }
     
     public boolean checkCode(String code)
    {
        PreparedStatement st;
        ResultSet rs;
        boolean code_exist = false;
        
        String query = "SELECT * FROM `reservations` WHERE `id` = ?";
        
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1,code);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                code_exist = true;
                
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"This Code does not exist, Try Again","Code Failed",2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return code_exist;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent_Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent_Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Cost;
    private javax.swing.JButton jButton_Rent;
    private com.toedter.calendar.JDateChooser jDateChooser_In;
    private com.toedter.calendar.JDateChooser jDateChooser_Out;
    private com.toedter.calendar.JDateChooser jDateChooser_Return;
    private com.toedter.calendar.JDateChooser jDateChooser_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_ATV;
    private javax.swing.JRadioButton jRadioButton_Car;
    private javax.swing.JRadioButton jRadioButton_Luxury;
    private javax.swing.JRadioButton jRadioButton_MotorCycle;
    private javax.swing.JRadioButton jRadioButton_Standard;
    private javax.swing.JRadioButton jRadioButton_Van;
    private javax.swing.JSpinner jSpinner_persons;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_id1;
    private javax.swing.JTextField jTextField_license;
    private javax.swing.JTextField jTextField_lname;
    // End of variables declaration//GEN-END:variables
}
